name: flutter_wanandroid
description: An wanandroid flutter client.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  shared_preferences: ^0.5.2
  transparent_image: ^0.1.0
  fluttertoast: ^3.0.1
  dio: ^2.1.2
  http: ^0.12.0+2
  lpinyin: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash01.jpg
    - assets/images/splash02.jpg
    - assets/images/splash03.jpg
    - assets/images/splash04.jpg
    - assets/images/splash05.jpg

  fonts:
  - family: Pacifico
    fonts:
    - asset: assets/fonts/Pacifico-Regular.ttf